### ISSUE TITLE
Incorrect named argument in callback function

### ISSUE THREAD

**Issue by adolfogc** [awslabs/aws-crt-python#120]
Hi,

According to the internal documentation, the named argument expected by the `_on_connection_resumed` callback is `return_code`, and not `error`, as currently used here:

https://github.com/awslabs/aws-crt-python/blob/2cd6b801fba4e0e3965d250460736e3b3e617328/awscrt/mqtt.py#L214

Internal documentation:
https://github.com/awslabs/aws-crt-python/blob/2cd6b801fba4e0e3965d250460736e3b3e617328/awscrt/mqtt.py#L120

See also the callback used in the test code:
https://github.com/awslabs/aws-crt-python/blob/2cd6b801fba4e0e3965d250460736e3b3e617328/mqtt_test.py#L40

Or the sample code from the related project `aws-iot-device-sdk-python-v2`:
https://github.com/aws/aws-iot-device-sdk-python-v2/blob/65454acdfaa2d28025ed0efe65965c14819c9e43/samples/pubsub.py#L68

**Comment by justinboswell** [comment]
Ported fix to a branch within awslabs so CI will run and allow merging.

**Comment by justinboswell** [comment]
Released, propagation to PyPi in the next few hours. https://github.com/awslabs/aws-crt-python/releases/tag/v0.5.9
