### ISSUE TITLE
Wheel for arm32v7?

### ISSUE THREAD

**Issue by adolfogc** [awslabs/aws-crt-python#122]
Hi, 

Do you plan on offering a wheel for arm32v7?

Best,
Adolfo

**Comment by JonathanHenson** [comment]
The pypi server for raspberry pi currently hosts armv7 builds of the crt. We haven’t finished adding them to our manylinux2014 distribution yet.

**Comment by adolfogc** [comment]
Hi @JonathanHenson, thanks for your reply. I only found it for aarch64, but I don't know if I'm looking at the right repository. Do you mean these files: https://pypi.org/project/awscrt/#files?

**Comment by JonathanHenson** [comment]
No theres  a separate repo for raspberry pi.

**Comment by adolfogc** [comment]
Is it this one (https://www.piwheels.org/project/awscrt/)? It didn't work for me, though. I'm currently building it from scratch, using this base Docker image: Debian Buster, Python 3.8,  https://hub.docker.com/r/arm32v7/python/.

**Comment by JonathanHenson** [comment]
We've updated our source to make sure the builds work for these architectures. Unfortunately we don't own piwheels.org so we need to both contact them to add python 3.8 and also come up with a backchannel distribution channel.

**Comment by adolfogc** [comment]
Hi @JonathanHenson,

Thanks! I quickly tried to install it from PiWheels using Python 3.7 and it worked.

```Docker
FROM arm32v7/python:3.7-slim-buster
RUN pip install awscrt --index-url https://www.piwheels.org/simple
```

I can continue building from scratch for Python 3.8 until PiWheels adds support for Python 3.8.
