### ISSUE TITLE
Set default QoS

### ISSUE THREAD

**Issue by burritoIand** [awslabs/aws-crt-python#126]
Hello, would it be possible to set a default QoS rather than setting it in each call?
https://github.com/awslabs/aws-crt-python/blob/master/awscrt/mqtt.py#L424

**Comment by bretambrose** [comment]
Hello,

I could see that being useful, but at the same time having multiple controls (default + optional per-pub/sub param) for one thing could also be confusing or lead to unexpected behavior (for example if you don't set a default and don't set the optional param, it's either an error (yuck) or you have to search CRT source to find out what the default-to-the-default qos is).  At worst, you could always wrap the Connection class with your own class that holds a default QoS and makes the appropriate call to the CRT Connection.

**Comment by burritoIand** [comment]
hey @bretambrose ok yeah I ended up going that route :) what about as an optional param to the builder e.g. "global_qos=1"? If it isn't present, then nothing changes, the qos would still need to be set, otherwise use it? In any case thanks!
```
        connection = mqtt_connection.connect()

        _publish = mqtt_connection.publish

        # wrap so we can set global QoS.
        def publish(topic, payload):
            return _publish(topic, payload, mqtt.QoS.AT_LEAST_ONCE)
        mqtt_connection.publish = publish

        connection.result()

        return mqtt_connection
```
