### ISSUE TITLE
SIGSEGV when calling mqtt.reconnect()

### ISSUE THREAD

**Issue by graebm** [awslabs/aws-crt-python#139]
Someone reached out to me, when their device lost connectivity they manually called `reconnect()`. This led to a segfault. (They were trying to reconnect faster because `reconnect_max_timeout_secs` wasn't working https://github.com/awslabs/aws-crt-python/issues/138)

Should reconnect() even be a public function? I honestly don't know without digging further. If not, this needs to be addressed in all the CRT libraries

**Comment by Hadatko** [comment]
I think reconnect is marked as deprecated feature. Directly in code

**Comment by Hadatko** [comment]
```
def reconnect(self):
        """DEPRECATED.

        awscrt.mqtt.ClientConnection automatically reconnects.
        To cease reconnect attempts, call disconnect().
        To resume the connection, call connect().
        """
```
