### ISSUE TITLE
Unable to install pip3install on fresh instance of jetpack (3.4) on Jetson Nano

### ISSUE THREAD

**Issue by JackSpade12** [awslabs/aws-crt-python#152]
I installed fresh JetPack 4.4 Developer Preview
then run the following commands:
1. sudo apt install python3-pip
2. sudo apt-get install libssl-dev
3. pip3 install awscrt

getting the following error
```
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libcrypto.a(sha512-armv8.o): In function `sha512_block_data_order':
    (.text+0x10c8): dangerous relocation: unsupported relocation
    collect2: error: ld returned 1 exit status
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

**Comment by JackSpade12** [comment]
was able to fix it by:
1. download the source file
2. change line 152 from '-DBUILD_SHARED_LIBS=OFF', to '-DBUILD_SHARED_LIBS=ON'
3. run python3 -m pip install

But this is wired workaround..

**Comment by JackSpade12** [comment]
Resolved 

to install pip I used
sudo apt install python3-pip

When I removed pip and installed it from the below website it all worked.
https://pip.pypa.io/en/stable/installing/

**Comment by mrtj** [comment]
I used `pip3 install awscrt` and it worked well. Before I tried to install with `python3 -m pip install awscrt` as described in the README but it caused the same "unsupported relocation" error.
