### ISSUE TITLE
errror compiling 0.6.0: libcrypto.a: error adding symbols: File format not recognized

### ISSUE THREAD

**Issue by marcosinig** [awslabs/aws-crt-python#162]
I am building for ARM A9 and I am getting this error:
bitbake aws-crt-python

/home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/lib/libcrypto.a: error adding symbols: File format not recognized

Below extensive log:
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Looking for stdint.h
| -- Looking for stdint.h - found
| -- Looking for stdbool.h
| -- Looking for stdbool.h - found
| -- Performing Test HAS_WGNU
| -- Performing Test HAS_WGNU - Failed
| -- Performing Test HAVE_SYSCONF
| -- Performing Test HAVE_SYSCONF - Success
| -- Performing Test HAS_SANITIZERS
| -- Performing Test HAS_SANITIZERS - Failed
| -- Looking for pthread.h
| -- Looking for pthread.h - found
| -- Looking for pthread_create
| -- Looking for pthread_create - not found
| -- Check if compiler accepts -pthread
| -- Check if compiler accepts -pthread - yes
| -- Found Threads: TRUE
| -- Found LibCrypto: /home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/lib/libcrypto.a
| -- LibCrypto Include Dir: /home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/include
| -- LibCrypto Shared Lib:  /home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/lib/libcrypto.so
| -- LibCrypto Static Lib:  /home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/lib/libcrypto.a
| -- Configuring done
| -- Generating done
| CMake Warning:
|   Manually-specified variables were not used by the project:
|
|     S2N_NO_PQ_ASM
| Scanning dependencies of target aws-c-http
| [  4%] Building C object CMakeFiles/aws-c-http.dir/source/connection.c.o
| [  8%] Building C object CMakeFiles/aws-c-http.dir/source/connection_manager.c.o
| [ 12%] Building C object CMakeFiles/aws-c-http.dir/source/connection_monitor.c.o
| [ 16%] Building C object CMakeFiles/aws-c-http.dir/source/h1_connection.c.o
| [ 20%] Building C object CMakeFiles/aws-c-http.dir/source/h1_decoder.c.o
| [ 24%] Building C object CMakeFiles/aws-c-http.dir/source/h1_encoder.c.o
| [ 28%] Building C object CMakeFiles/aws-c-http.dir/source/h1_stream.c.o
| [ 32%] Building C object CMakeFiles/aws-c-http.dir/source/h2_connection.c.o
| [ 36%] Building C object CMakeFiles/aws-c-http.dir/source/h2_decoder.c.o
| [ 40%] Building C object CMakeFiles/aws-c-http.dir/source/h2_frames.c.o
| [ 44%] Building C object CMakeFiles/aws-c-http.dir/source/h2_stream.c.o
| [ 48%] Building C object CMakeFiles/aws-c-http.dir/source/hpack.c.o   
| [ 52%] Building C object CMakeFiles/aws-c-http.dir/source/hpack_huffman_static.c.o
| [ 56%] Building C object CMakeFiles/aws-c-http.dir/source/http.c.o
| [ 60%] Building C object CMakeFiles/aws-c-http.dir/source/proxy_connection.c.o
| [ 64%] Building C object CMakeFiles/aws-c-http.dir/source/request_response.c.o
| [ 68%] Building C object CMakeFiles/aws-c-http.dir/source/statistics.c.o
| [ 72%] Building C object CMakeFiles/aws-c-http.dir/source/strutil.c.o 
| [ 76%] Building C object CMakeFiles/aws-c-http.dir/source/websocket.c.o
| [ 80%] Building C object CMakeFiles/aws-c-http.dir/source/websocket_bootstrap.c.o
| [ 84%] Building C object CMakeFiles/aws-c-http.dir/source/websocket_decoder.c.o
| [ 88%] Building C object CMakeFiles/aws-c-http.dir/source/websocket_encoder.c.o
| [ 92%] Linking C static library libaws-c-http.a
| [ 92%] Built target aws-c-http
| Scanning dependencies of target elasticurl
| [ 96%] Building C object bin/elasticurl/CMakeFiles/elasticurl.dir/main.c.o
| [100%] Linking C executable elasticurl
| /home/user/yocto/pyro/build/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/aws-crt-python/0.6.0-r0/recipe-sysroot-native/usr/lib/libcrypto.a: error adding symbols: File format not recognized
| collect2: error: ld returned 1 exit status
| bin/elasticurl/CMakeFiles/elasticurl.dir/build.make:100: recipe for target 'bin/elasticurl/elasticurl' failed
| make[2]: *** [bin/elasticurl/elasticurl] Error 1
| CMakeFiles/Makefile2:122: recipe for target 'bin/elasticurl/CMakeFiles/elasticurl.dir/all' failed
| make[1]: *** [bin/elasticurl/CMakeFiles/elasticurl.dir/all] Error 2   
| Makefile:127: recipe for target 'all' failed
| make: *** [all] Error 2
| /home/user/yocto/pyro/build/tmp/wor

**Comment by bretambrose** [comment]
My first guess is some kind of platform/target mismatch between how cmake has been invoked and the libcrypto it's discovering.  My guess is that the libcrypto path is a cross-compiled toolchain artifact, so possibly the cmake invocation through bitbake is not actually setting up the cross compile correctly and so it's building the SDK for the local platform but trying to link against an ARM binary (or vice versa is another possibility I guess).  Not knowing much about bitbake, your local configuration, or your cross-compile toolchain, it's hard to tell how cmake has been invoked.

Is there any other information you can provide (wrt Bitbake, etc...) that would let us try and recreate this?

**Comment by sandeep-shyam** [comment]
i am facing similar issue while installing awscrt from source, 
    CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
      Could NOT find LibCrypto (missing: LibCrypto_LIBRARY LibCrypto_INCLUDE_DIR)

any workaround on my ARMv7 Processor SBC would be really helpful, 
my configuration : QCT APQ8064 CDP
