### ISSUE TITLE
awscrt fails for python >= 3.7 on aarch64-linux

### ISSUE THREAD

**Issue by shravan097** [awslabs/aws-crt-python#171]
I am currently running Ubuntu 19.10 aarch64-linux on  i.MX 8QM MEK. We ran our code on python 3.6 but recently we upgraded to python 3.7. After our upgrade, we noticed that `pip3 install awsiotsdk` fails because `awscrt` installation fails. 

I tested this by creating two virtual python environment, one using python3.6 and other using python3.7. After switching the source and installing awsiotsdk on both virtual environment, the installation succeeded on python 3.6 virtual env but the installation failed on python 3.7.

Please let me know any solution to this.
Thanx.

**Comment by bretambrose** [comment]
Is there output/logs/error text?

**Comment by bretambrose** [comment]
Looking further, it appears that the 3.7 wheel builds are failing.

**Comment by shravan097** [comment]
Hey @bretambrose, thanx for your reply. Yes the wheels fails. Please find the console output attached as zip.  Note that I am using python 3.7 virtual env here and I am installing from requirements.txt which consist awsiotsdk.  I thought about following  
https://github.com/aws/aws-iot-device-sdk-python-v2/issues/87#issuecomment-656262800 but I should not have to do that for aarch64 env running python 3.7.  I believe that since awsiotsdk works on python 3.6 but it should work for 3.7.

[Archive.zip](https://github.com/awslabs/aws-crt-python/files/5070462/Archive.zip)

**Comment by shravan097** [comment]
After looking through, looks like my `pip` was not up to date. After upgrading the `pip`, everything works.

**Comment by mkozjak** [comment]
@shravan097 to what version did you upgrade everything? Having same trouble on Simatic IOT2050.

**Comment by shravan097** [comment]
@mkozjak I am on the latest pip version which I believe is `20.2.3`. I performed `pip3 install --upgrade pip` and then did `pip3 install awsiotsdk`. Hope this helps.

**Comment by Samuelpenner** [comment]
> After looking through, looks like my `pip` was not up to date. After upgrading the `pip`, everything works.

This worked! Spent hours trying to figure this issue out and thankfully came across this. Solid pop update cured my issues!
