### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by Yaronn44** [awslabs/aws-crt-python#176]
Hello,
We are using  the lib : [awsiotsdk2](https://github.com/aws/aws-iot-device-sdk-python-v2) in order to connect our AWS IoT things to our server.
We also use a Twisted server to manage the connections.
However, when the connect/disconnect workflow for our things was implemented with the old [awsiotsdk](https://github.com/aws/aws-iot-device-sdk-python) we had no problem except everything was really slow as it was in full Python...
Since we use the new lib, it's seems better but we clearly encounter a memory leak we can't resolve.
Our code is almost exactly as the `pubsub.py` example so I don't know where we could make something wrong.

It's seems that the `mqtt_client.disconnect()` doesn't clean up all resources and keep stocking some informations.

If we follow what the code do:
```
def disconnect(self):
    """Close the connection (async).

    Returns:
        concurrent.futures.Future: Future which completes when the connection is closed.
        The future will contain an empty dict.
    """

    future = Future()

    def on_disconnect():
        future.set_result(dict())

    try:
        _awscrt.mqtt_client_connection_disconnect(self._binding, on_disconnect)
    except Exception as e:
        future.set_exception(e)

    return future
```

And when we look at the [aws-c-mqtt](https://github.com/awslabs/aws-c-mqtt) lib, it's said in the README that:

```
int aws_mqtt_client_connection_disconnect(struct aws_mqtt_client_connection *connection);

Closes an open connection. Does not clean up any resources, that's to be done by aws_mqtt_client_connection_destroy, probably from the on_disconnected connection callback.
```

It's look like exactly the problem we encounter: not all resources are cleaned up.
But the `aws_mqtt_client_connection_destroy` is never call in the `on_disconnected` callback.

Do you plan to manage this case and implement it soon?

**Comment by bretambrose** [comment]
disconnect and destroy are separate and destroy will not be called as a part of user-initiated disconnect.  Destroy is only initiated when the reference count to the python object goes to zero.  If it seems like there's a leak and destroy is not getting called, then likely something in Python-land is still referring to the connection.

**Comment by Yaronn44** [comment]
Thank you for your response. I'll try that, stay in touch and notify you of my results.
