### ISSUE TITLE
Runtime link issue with: libpthread_atfork

### ISSUE THREAD

**Issue by marklombardi** [awslabs/aws-crt-python#190]
Hello There,
I appear to be having a runtime link issue with the **awscrt** library not being able to locate the pthread_atfork( ) function.

I am running on an embedded ARM v7 device.

This is the error I receive when running the python3 script:

>ImportError: /usr/lib/python3.5/site-packages/_awscrt.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: pthread_atfork`

>root@dev:/lib# nm -D libpthread.so.0  | grep pthread_atfork
>root@dev:/lib# nm -D /usr/lib/libpthread_nonshared.a  | grep pthread_atfork
>root@dev:/lib# nm -D /usr/lib/libpthread_nonshared.a 
>
>pthread_atfork.oS:
>nm: pthread_atfork.oS: no symbols

>root@dev:/lib# more /usr/lib/libpthread  
>libpthread.so           libpthread_nonshared.a  
>root@dev:/lib# more /usr/lib/libpthread.so 
>/* GNU ld script
>   Use the shared library, but some functions are only in
>   the static library, so try that secondarily.  */
>OUTPUT_FORMAT(elf32-littlearm)
>GROUP ( ../../lib/libpthread.so.0 ./libpthread_nonshared.a )
>root@dev:/lib#  `

These are the packages that were built:
>    /usr/lib/python3.5/site-packages/_awscrt.cpython-35m-arm-linux-gnueabihf.so
>    /usr/lib/python3.5/site-packages/awscrt-0.9.0.dist-info/*
>    /usr/lib/python3.5/site-packages/awscrt/*

Any help would be much appreciated!

**Comment by marklombardi** [comment]
It looks like there is a simple fix for this issue by linking with: **-lpthread_nonshared** (libc on other platforms) when necessary and/or changing the link order of the libraries. Perhaps you need a CMake rule to determine which library to link against on different platforms?

"_So the phrase is something like target_link_libraries(cmake pthread_nonshared) and it goes in CMakeList.txt ?_"

Similar issues identified and fixed [https://gitlab.kitware.com/cmake/cmake/-/issues/20709](here) and [https://github.com/openssl/openssl/issues/3884](here)

**Comment by marklombardi** [comment]
If anyone else comes across this issue, the fix is as follows:

1. Uninstall any old versions of awscrt
python3 -m pip uninstall awscrt

2. Setup DevTools
`export CC=arm-linux-gnueabihf-gcc
export CMAKE_PREFIX_PATH=/lib;/usr/lib/`

3. Clone the Repository
`git clone https://github.com/awslabs/aws-crt-python.git
cd aws-crt-python
git submodule update --init
`

4. Apply the following patch to setup.py:
`    else:  # unix
        # linker will prefer shared libraries over static if it can find both.
        # force linker to choose static variant by using using "-l:lib<name>.a" syntax instead of just "-lcrypto".
        libraries = [':lib{}.a'.format(x) for x in libraries]
        libraries += [':libcrypto.a', 'rt']
>>   if is_arm():
>>       libraries += [':libpthread_nonshared.a']`

5. Rebuild the library
`python3 -m pip install .`

Problem solved.

**Comment by bretambrose** [comment]
This is good guidance if anyone else stumbles into this situation but I'm going to go ahead and close this for now.
