### ISSUE TITLE
GLIBC_2.28 not found required by awscrt

### ISSUE THREAD

**Issue by fiLLLip** [awslabs/aws-crt-python#223]
Currently transitioning to GreengrassV2 and needed to use https://github.com/aws/aws-iot-device-sdk-python-v2 for a connection to MQTT. We are using Kunbus Revpi that are based on Raspbian Strech images, and have LIBC 2.24 as latest version. We cannot upgrade to Buster because of dependencies not yet ready in the Revpi images (they don't officially support it yet I guess). Is there any specific reason that 2.28 is required, or could it be downgraded to 2.24 for backwards compatibility?

```
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /greengrass/v2/work/com.test.test/venv/lib/python3.7/site-packages/_awscrt.cpython-37m-arm-linux-gnueabihf.so). 
```

**Comment by JonathanHenson** [comment]
It’s not required. Are you building from source or using the prebuilt wheels? If not, It’s likely you’re building with a later version of libc than exists on the device you’re deploying to.

**Comment by fiLLLip** [comment]
We used the prebuilt wheels I guess. We at least did not make an active choice to build from source. Do prebuilt for Raspbian Stretch exist?

**Comment by fiLLLip** [comment]
I have to reflash my device to test this, but, is it correct that setuptools do not fetch prebuilt wheels, and always tries to build the packages? https://stackoverflow.com/questions/30686069/doesnt-setup-py-develop-use-wheel-for-install-requires/44446114#44446114

If so, that would explain why it tries to build when using pip to install `awsiotsdk`: https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/setup.py

We'll try to manually include `awscrt` in our requirements file and see how it goes.

**Comment by JonathanHenson** [comment]
It should be pulling the wheel if it exists. We don’t get to manage the raspbian pypi distribution, raspbian pulls from the main pypi, builds and uploads asynchronously to us. We should check there and see what’s going on.

maybe make sure setuptools is updated to latest and see what happens?

**Comment by fiLLLip** [comment]
We'll do some explorations and report back :)
