### ISSUE TITLE
Changing master to main has broken other projects

### ISSUE THREAD

**Issue by kennu** [awslabs/aws-crt-python#227]
It seems this project has renamed the master branch to main, which has broken a downstream project at https://github.com/aws/meta-aws/blob/zeus/recipes-crt/aws-crt-python/aws-crt-python.inc

This is a big problem in IoT development that depends on a specific branch (zeus) of the downstream project.

**Comment by bretambrose** [comment]
Migration from master -> main is/was a mandatory AWS-wide initiative.  I would suggest opening an issue on the downstream library.

**Comment by kennu** [comment]
Yeah, I just wanted to inform you that it's causing problems to your customers.
