### ISSUE TITLE
Handling Policy violations: What does AWS_ERROR_MQTT_UNEXPECTED_HANGUP actually mean?

### ISSUE THREAD

**Issue by avwhite** [awslabs/aws-crt-python#229]
I have a program which connects to AWS IoT, then runs a loop where it tries to poll information from a database and if it finds some it publishes it to an MQTT topic.

It generally works great.

I have discovered however, that if the policy attached to the certificate does not allow the client to publish on that topic, the client gets disconnected with the error: `AwsCrtError(name='AWS_ERROR_MQTT_UNEXPECTED_HANGUP', message='The connection was closed unexpectedly.', code=5134)`. Then it immediately automatically reconnects, then immediately tries to resend the message (probably because QoS is 1)  and then it immediately gets disconnected again with the same error for the same reason.

This creates a bit of an unfortunate loop where the client spams connections to the AWS IoT service really quickly.

Even if the just attaching the right policy works, I would still ideally like the code to behave a bit nicer in this error case.

My main idea is to simply disconnect and stop trying to connect until the system (client) is restarted next time when the `AWS_ERROR_MQTT_UNEXPECTED_HANGUP` error happens.

But before doing that, I would like to know what that error actually means? I cannot find documentation on it anywhere.

What I hope is that I can count on it only happening when something is wrong with the server (bug or a policy(or other circumstance) which does not allow the client to do what it wants). In that case it is reasonable (in my system) for the client to simply give up.

What I fear is that it is some kind of catch-all error which can happen for any number of reasons, some for which retrying is the correct thing to do and some for which giving up is the correct thing to do and that I cannot distinguish them.

Another approach which could maybe work is having some pretty aggressive slow-down on publish retries. I know this can be done with connection attempts, but is it possible to do it with publish attempts under QoS=1?

**Comment by bretambrose** [comment]
Unfortunately your fear is correct.  AWS IoT Core can hang up the connection for a large number of reasons and the client is given no clue as to why it happened.

We currently have on our radar some behavior improvements to lower the potential cost of the reconnect failure loop (do exponential backoff even on a successful connection if the the connection is closed relatively quickly) but as it currently stands, on the client side there is nothing accurate we can surface to you to help you diagnose the connection issue.

**Comment by avwhite** [comment]
Thanks for the reply.

To anyone else who finds this, I have found stopping reconnect attempts on the unexpected hangup works well enough in practice for this particular use case.

**Comment by mealmeida** [comment]
Did you get any additional information on this issues?
