### ISSUE TITLE
Out-of-memory when building wheels for ARMHF

### ISSUE THREAD

**Issue by jensengillett** [awslabs/aws-crt-python#230]
I'm currently trying to install aws-crt on a Hummingboard CBi (i.MX6-based, dual-core ARMHF w/ 1gb ram) and keep failing to finish building wheels as the system runs out of memory thanks to spawning 200+ cmake processes, causing the system to quickly run out of memory, attempt to reap processes, and eventually restart. Is there any way that the wheel compile can be switched to a single-thread task so that the board doesn't kill itself, or how would I go about cross-compiling the wheels on a different machine?

Here's the task state when memory runs out, it's pretty obvious the 200+ processes are the cause of the OoM.
[killed.txt](https://github.com/awslabs/aws-crt-python/files/5859160/killed.txt)

**Comment by rpcme** [comment]
Hello @jensengillett - are you using a Yocto built image?  Or Debian?  If using Yocto, you can build it from your distribution using the meta-aws project https://github.com/aws/meta-aws

**Comment by jensengillett** [comment]
I'm using Debian, though at this point the problem is moot as I have switched to an i.MX8-based platform (arm64) instead. Thanks for getting back to me though!
