### ISSUE TITLE
Error Linking libcrypto.a: error adding symbols: File format not recognised

### ISSUE THREAD

**Issue by marklombardi** [awslabs/aws-crt-python#246]
This appears to be a duplicate of this issue, however that issue has been closed. https://github.com/awslabs/aws-crt-python/issues/162

I have attached the build log and Bitbake Recipe.

[log_do_compile.12954](https://gist.github.com/marklombardi/199ed1ea412db5dbda4660665417250d)
[awscrt_0.10.8.bb](https://gist.github.com/marklombardi/be1869f60af27a0cad86922715d0c2a0)

**Comment by Firefox2005** [comment]
I experience the same issue.

**Comment by graebm** [comment]
as of version 0.11.x awscrt compiles its own libcrypto.a, instead of relying on a user-installed libcrypto

Hopefully this fixes things!
