### ISSUE TITLE
Can't use some special characters in profile_name when creating a profile auth provider

### ISSUE THREAD

**Issue by somq** [awslabs/aws-crt-python#303]
Some special characters such as "@" or "/" in `profile_name` return an error when trying to create a profile auth provider.

Error:
```log
Traceback (most recent call last):
  File "mock_device.py", line 845, in <module>
    credentials_provider = auth.AwsCredentialsProvider.new_profile(
  File "/home/REDACTED/.local/share/virtualenvs/REDACTED-zaVS8qFu/lib/python3.8/site-packages/awscrt/auth.py", line 205, in new_profile
    binding = _awscrt.credentials_provider_new_profile(
RuntimeError: 0 (AWS_ERROR_SUCCESS): Success.
```

Relevant code:
```py
from awscrt import auth, io

# Spin up resources
event_loop_group = io.EventLoopGroup(1)
host_resolver = io.DefaultHostResolver(event_loop_group)
client_bootstrap = io.ClientBootstrap(event_loop_group, host_resolver)

credentials_provider = auth.AwsCredentialsProvider.new_profile(
    client_bootstrap=client_bootstrap,
    profile_name="user@123456789012",
    config_filepath='~/.aws/config',
    credentials_filepath='~/.aws/credentials'
)
# ... use creds somewhere
```

Some further details:

- File encoding is ok (UTF-8)
- The `profile_name` is correctly passed to the lib (string print in `/home/REDACTED/.local/share/virtualenvs/REDACTED-zaVS8qFu/lib/python3.8/site-packages/awscrt/auth.py` is ok)
- latest version used (0.11.25)

Thanks for your help!

**Comment by bretambrose** [comment]
By definition (of an internal spec that I don't believe is visible outside Amazon internal unfortunately), profile names are limited to alphanumeric and "-", "_"  That being said, there is clearly something getting lost in the error surfacing as AWS_ERROR_SUCCESS is not very useful.
