### ISSUE TITLE
getting error for dependency on awscrt 

### ISSUE THREAD

**Issue by enliminal** [awslabs/aws-crt-python#328]
I have been having issues using python to send message to AWS IOT. The certs are valid and I can use the AWS CLI2. When I use python, I get the following error. 
```
`==>  python3 pubsub.py --endpoint XXXXXXXXXXXXXXXX-ats.iot.us-east-1.amazonaws.com --root-ca ../../x509.pem --cert ../../123456789-certificate.pem.crt --key ../../123456789-private.pem.key

Traceback (most recent call last):
  File "/Users/bahramsa/projects/bahram/aws/awesomebuilder/scripts/aws-iot-device-sdk-python-v2/samples/pubsub.py", line 5, in <module>
    from awscrt import io, mqtt, auth, http
  File "/opt/homebrew/lib/python3.9/site-packages/awscrt/io.py", line 11, in <module>
    import _awscrt
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/_awscrt.cpython-39-darwin.so, 2): Symbol not found: _aws_hash_ptr
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/_awscrt.cpython-39-darwin.so
  Expected in: flat namespace
 in `/opt/homebrew/lib/python3.9/site-packages/_awscrt.cpython-39-darwin.so`
 ```
 
 I even tried virtualenv but still have the same issue.
 
 I then tried to pull the awscrt repo and build it. Now I get the following error: 
 
 ```
 DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /Users/bahramsa/projects/aws-crt-python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: awscrt
  Building wheel for awscrt (setup.py) ... done
  Created wheel for awscrt: filename=awscrt-1.0.0.dev0-cp39-cp39-macosx_11_0_arm64.whl size=526127 sha256=80119d092cf73fe3998511c0af3375a650833bef6db7f07ce1367a48341be50e
  Stored in directory: /Users/bahramsa/Library/Caches/pip/wheels/df/33/f0/b6f70c3d7bf6f6e4925940ab941e65cfbed6b39b77578ec8b4
Successfully built awscrt
Installing collected packages: awscrt
  Attempting uninstall: awscrt
    Found existing installation: awscrt 0.13.0
    Uninstalling awscrt-0.13.0:
      Successfully uninstalled awscrt-0.13.0
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awsiotsdk 1.0.0.dev0 requires awscrt==0.13.0, but you have awscrt 1.0.0.dev0 which is incompatible.

```

I have uninstalled awscrt multiple times and still get the error. 
Macbook Pro, Monterey 12.1, M1 Chip.

**Comment by mogryzko-chewie** [comment]
Have you tried enabling your terminal to use Rosetta and then re-installing? https://www.bigbinary.com/learn-rubyonrails-book/setting-up-mac#enable-rosetta-for-terminal-on-m1-mac

**Comment by kvncp** [comment]
I verified that this is an issue with 0.13.0. Installing 0.12.0 instead works successfully, but you'll end up with the same error from aws-iot-sdk since they pin the 0.13 version.

**Comment by ann8ty** [comment]
This was working last week and when I reset my venv what I had working stopped today. :/ I think previously all I needed to do was update pip.  That didn't work today.

I did something hacky to get it mostly working again, downloaded the 0.13.0 source zip, changed the version in the file so it built v0.13.0 and built using the README instructions.  This got around the pip dependency error.  awsiotsdk==1.8.0 installed happily on top of it.  I am sure to pay for this hack later.  

Also Macbook Pro, Monterey 12.1, Apple M1 Pro chip.

**Comment by jamesrusso** [comment]
> Have you tried enabling your terminal to use Rosetta and then re-installing? https://www.bigbinary.com/learn-rubyonrails-book/setting-up-mac#enable-rosetta-for-terminal-on-m1-mac

I'd prefer to stick with ARM completely if I could.

**Comment by jmklix** [comment]
Can you confirm if this is still an issue with M1? Support for M1 has been added since this issue was opened

**Comment by nikiitat** [comment]
Still getting this issue on M1:
- Installing awscrt (0.13.6): Failed

**Comment by bretambrose** [comment]
M1 support was added in 0.13.11
