### ISSUE TITLE
auth.AwsCredentialsProvider - Using AWS SSO profile?

### ISSUE THREAD

**Issue by cgddrd-gardin** [awslabs/aws-crt-python#335]
Hi, 

I'm hoping that there's a way of using `awscrt.auth.AwsCredentialsProvider` to authenticate a Python app that communicates with IoT Core/Shadow Service using an AWS SSO profile, rather that requiring a sytatic set of IAM credentials (access key/secret pair) in an `~/.aws/credentials` file. 

Is this possible?

Many thanks.

**Comment by bretambrose** [comment]
The aws-c-* libraries don't implement an SSO-based credentials provider yet, so you can't do that directly.  However, you should be able to use the standard AWS SDK for python SSO provider implementation and wrap that in a delegate provider that defers to the Python SDK provider: https://github.com/awslabs/aws-crt-python/blob/main/awscrt/auth.py#L282.

**Comment by broglep-work** [comment]
in case somebody else stumbles upon this, here is an implementation of a credentials provider that delegates to standard AWS SDK. It should be reasonably solid, but is not really battle tested:

https://gist.github.com/broglep-work/1835d8c9465e83d177097f467d82df17
