### ISSUE TITLE
AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE: TLS (SSL) negotiation failed

### ISSUE THREAD

**Issue by yigit-bwise** [awslabs/aws-crt-python#348]
Hi,

I am using awscrt to connect mqtt client. All of a sudden I started getting this error, without changing a line in my code or changing the previously working certificates: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE: TLS (SSL) negotiation failed

This is thrown when client tries to connect to mqtt builder

```
mqtt_connection = mqtt_connection_builder.mtls_from_path(
            endpoint=ENDPOINT,
            cert_filepath=PATH_TO_CERTIFICATE,
            pri_key_filepath=PATH_TO_PRIVATE_KEY,
            client_bootstrap=client_bootstrap,
            ca_filepath=PATH_TO_AMAZON_ROOT_CA_1,
            client_id=CLIENT_ID,
            clean_session=False,
            keep_alive_secs=6
            )

mqtt_connection.connect()
```

This error does NOT occur if I use the older version with AWSIoTMQTTClient.

**Comment by bretambrose** [comment]
There's no way of telling what's going on without more information.  Debug-level CRT logs (https://github.com/awslabs/aws-crt-python/blob/main/awscrt/io.py#L27) would give a much better picture of what is failing.

**Comment by bretambrose** [comment]
Closing absent further information
