### ISSUE TITLE
library git submodules point to latest?

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-crt-python#361]
Hi, as we integrate your software into [meta-aws](https://github.com/aws4embeddedlinux/meta-aws) - a yocto layer.
I was wondering if you really point to the latest referenced git repo when building - you suppose
`git clone https://github.com/awslabs/aws-crt-python.git`
`cd aws-crt-python`
`git submodule update --init`
I'm asking since we take care of reproducibility for the software we build.
If you really just take the latest this is not possible.
We made a  [patch](https://github.com/aws4embeddedlinux/meta-aws/commit/9efba45b56ca8d1920e609203328db7ddfa0a04b) disable the building of the libraries and take the ones we build separately. May you can add a switch in the setup.py to allow this and make our patch obsolete. We also added the patch since not all CMAKE env variables were set correctly building the libs (aws-lc) your way for arch arm.
A last note - using distutils is deprecated as you probably know.

**Comment by bretambrose** [comment]
Not sure I follow the question.  The submodules underneath the crt are not necessarily the latest.  They're a snapshot of releases that currently work together.  Multiple teams update them on a basis needed to release features and bug fixes.
