### ISSUE TITLE
awscrt archive is broken on pypi.org website

### ISSUE THREAD

**Issue by HiGein** [awslabs/aws-crt-python#362]
The awscrt tar.gz archive is corrupted: https://pypi.org/project/awscrt/#files

https://files.pythonhosted.org/packages/69/f6/f09b1035951a9dff428d9606aa361a78437fbb2572d22059c7adfff576f1/awscrt-0.13.11.tar.gz

The following versions have the same issue as well: awscrt-0.12.5, awscrt-0.13.8, awscrt-0.13.9. Probably, this affects some other versions. While the archive can be opened, it is corrupted, and it is not clear whether all the files exist in it. I would be grateful if you could fix that. I've checked the other packages of awscommonruntime maintainer, and they are ok. The issue is only with awscrt archive on pypi.org website. Thank you.

**Comment by nateprewitt** [comment]
@HiGein you may need to include info on how you're decompressing the tar files and operating system. I'm unable to reproduce this on macOS or Windows.

**Comment by HiGein** [comment]
With bsdtar 3.6.1 I'm getting the following error:
```
bsdtar: Pathname can't be converted from UTF-8 to current locale.
x awscrt-0.13.11/crt/aws-c-common/tests/resources/\303\205 \303\211xample.txt
```
This probably is the issue within my system.

**Comment by HiGein** [comment]
So, bsdtar (and, probably, ark) are not able to unarchive properly because of the file containing non-ascii characters in its name: https://github.com/awslabs/aws-c-common/blob/main/tests/resources/%C3%85%20%C3%89xample.txt

**Comment by nateprewitt** [comment]
Filesystems are definitely not guaranteed to be ascii compliant these days. It looks like that file has been added to test the CRT works as expected with non-ascii files. This appears to be a limitation/incorrect expectation by ark/bsdtar. I don't know if the CRT has much it can do here.

**Comment by HiGein** [comment]
Closing this since this is local configuration issue.
bsdtar works without errors if locales are properly configured on the system
https://unix.stackexchange.com/questions/418141/arch-linux-failed-to-set-locale-fix-your-system/

**Comment by HiGein** [comment]
BTW, if someone would like to create PKGBUILD of this package on Arch Linux in order to set up aws-cli-v2, there's another option: just to install aws-cli-v2-bin.
