### ISSUE TITLE
Linker flag fatal_warnings ought to be fatal-warnings

### ISSUE THREAD

**Issue by hxw** [awslabs/aws-crt-python#366]
This line cause linker Error when compiling with clang:
```
ld: error: unknown argument '-fatal_warnings', did you mean '-fatal-warnings'
```

https://github.com/awslabs/aws-crt-python/blob/e07efb497ea76df105aba0b2ef2d02b6adf51ef5/setup.py#L318

according to the ld man page (both clang and GNU) this should be `fatal-warnings`

**Comment by timblaktu** [comment]
I'm stumbling over this too, @hxw, tracked it down to [this commit](https://github.com/awslabs/aws-crt-python/pull/356/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R301). I'm going to try to fork and fix..

**Comment by bretambrose** [comment]
The additional platform checks around the variants of that linker flag should address this.  Reopen if this is not the case.
