### ISSUE TITLE
Publish with retain=True fails

### ISSUE THREAD

**Issue by andypapas** [awslabs/aws-crt-python#367]
We have a use case where we want to publish messages with retain=True.
We have tried it from the AWS console and it seems to work correctly.
However, when trying this from this library(tested latest version & python3.8) it throws errors and the messages never arrive to the client.

Looking at the unit tests, it doesn't look like this is tested (or maybe I failed to spot them).
Is retain=True on publish supposed to be working?

**Comment by gdesrocherspbsc** [comment]
I have the same issue with Python 3.10 and latest version. The connection is dropping after device tries to publish a retain message

**Comment by bretambrose** [comment]
Just checked this now and did not see any issue with retain behavior.  If you have debug-level CRT logs or reliable repro steps, we can investigate further.

**Comment by bretambrose** [comment]
Closing absent further information
