### ISSUE TITLE
Errors during install on macOS with XCode/clang 14+

### ISSUE THREAD

**Issue by jameshalsall** [awslabs/aws-crt-python#410]
After installing latest XCode, which also updated `clang` to version 14, I see the following error when installing the package:

```
...
clang -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/jameshalsall/.pyenv/versions/3.8.13/lib -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/jameshalsall/.pyenv/versions/3.8.13/lib -L/opt/homebrew/lib -Wl,-rpath,/opt/homebrew/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib build/temp.macosx-12.5-arm64-cpython-38/source/auth_credentials.o build/temp.macosx-12.5-arm64-cpython-38/source/auth_signer.o build/temp.macosx-12.5-arm64-cpython-38/source/auth_signing_config.o build/temp.macosx-12.5-arm64-cpython-38/source/common.o build/temp.macosx-12.5-arm64-cpython-38/source/crc.o build/temp.macosx-12.5-arm64-cpython-38/source/crypto.o build/temp.macosx-12.5-arm64-cpython-38/source/event_stream_headers.o build/temp.macosx-12.5-arm64-cpython-38/source/event_stream_rpc_client_connection.o build/temp.macosx-12.5-arm64-cpython-38/source/event_stream_rpc_client_continuation.o build/temp.macosx-12.5-arm64-cpython-38/source/http_connection.o build/temp.macosx-12.5-arm64-cpython-38/source/http_headers.o build/temp.macosx-12.5-arm64-cpython-38/source/http_message.o build/temp.macosx-12.5-arm64-cpython-38/source/http_proxy.o build/temp.macosx-12.5-arm64-cpython-38/source/http_stream.o build/temp.macosx-12.5-arm64-cpython-38/source/io.o build/temp.macosx-12.5-arm64-cpython-38/source/module.o build/temp.macosx-12.5-arm64-cpython-38/source/mqtt_client.o build/temp.macosx-12.5-arm64-cpython-38/source/mqtt_client_connection.o build/temp.macosx-12.5-arm64-cpython-38/source/pkcs11_lib.o build/temp.macosx-12.5-arm64-cpython-38/source/s3_client.o build/temp.macosx-12.5-arm64-cpython-38/source/s3_meta_request.o -Lbuild/temp.macosx-12.5-arm64-cpython-38/deps/install/lib -laws-c-s3 -laws-c-mqtt -laws-c-auth -laws-c-http -laws-c-event-stream -laws-c-compression -laws-checksums -laws-c-io -laws-c-cal -laws-c-sdkutils -laws-c-common -o build/lib.macosx-12.5-arm64-cpython-38/_awscrt.cpython-38-darwin.so -framework Security -Wl,-fatal_warnings
        ld: warning: -undefined dynamic_lookup may not work with chained fixups
        ld: fatal warning(s) induced error (-fatal_warnings)
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for awscrt
  Failed to build awscrt
```

**Comment by fpottbaecker** [comment]
This seems to be an issue with setuptools, as this error occurs when setuptools is building the `_awscrt` extension, they include `-undefined dynamic_lookup` per default.

**Comment by jameshalsall** [comment]
Ahh good to know, thank you! I will do some digging

**Comment by jre21** [comment]
This issue is being tracked upstream at https://github.com/python/cpython/issues/97524 .  The conclusion seems to be that Apple will have a proper fix in some future SDK release and has no plans to break current use before then.  In the meantime, could the developers update setup.py to not set [fatal-warnings](https://github.com/awslabs/aws-crt-python/blob/main/setup.py#L323) on macOS, so users are at least not caught in the middle of all this?

**Comment by graebm** [comment]
could you please share the FULL verbose output of your build:
`python3 -m pip install --verbose awscrt`

Also, it would be good to see the details of your python installation, can you share the output of:
`python3 -m sysconfig`

You can attach these as text files. They'll each be pretty long

**Comment by graebm** [comment]
Apologies about the "fatal warnings". Compiler warnings are no longer fatal for users simply installing this library.

We made that change in [v0.15.2](https://github.com/awslabs/aws-crt-python/compare/v0.15.1...v0.15.2#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R315) (now warnings are only fatal in the "development" builds my team uses locally while writing this code: `pip install --editable .` or `python3 setup.py develop`).

**Comment by dgilman** [comment]
If the warnings as errors is off in 0.15.2 it sounds like this ticket can be closed and the issue can be taken up with awscli2 (who are pinning 0.14.0) and MacPorts (which is doing the same, and I'm going to go ahead and bump it there to fix this).

Note that [0.14.0 is pinned in awscli2](https://github.com/aws/aws-cli/blob/v2/pyproject.toml#L36). If you install awscli2 via the pyinstaller all-in-one package you get a prebuilt 0.14.0, and if you use pip to install awscli2 you'll get a pre-built 0.14.0 wheel most of the time. These were all presumably built with older Xcode and sidestepped this whole issue.

If someone out there is installing awscli2 via pip, and they can't/won't use the pre-built wheel, and they're on the newer Xcode, it'll try to compile 0.14.0 and blow up. That's a problem with awscli2 and not relevant to this ticket but sounds like a good reason to bump the pinning in awscli2.

**Comment by graebm** [comment]
I've alerted the CLI team that they should stop pinning to the older version of `awscrt`
I'll keep this ticket open until they make the upgrade

**Comment by graebm** [comment]
OK, this is fixed in awscli2: https://github.com/aws/aws-cli/pull/7522
Their next release goes out tomorrow

I guess now it's just a waiting game for places like MacPorts to pull in newer versions
