### ISSUE TITLE
incorrect version in the package metadata

### ISSUE THREAD

**Issue by gdamjan** [awslabs/aws-crt-python#412]
running `pip check` complains about:
```
python -m pip check
awscli 2.8.12 has requirement awscrt<=0.14.0,>=0.12.4, but you have awscrt 1.0.0.dev0.
```

digging a bit more, it seems that awscrt has a fixed "Version" in its metadata, created here, a year and half ago:
https://github.com/awslabs/aws-crt-python/commit/56c431b5790d71369fed4babb68fa3f942557769

**Comment by nateprewitt** [comment]
Hi @gdamjan,

It looks like you're trying to install the awscrt directly from Github. The version supplied here is the dev designation, it is transformed at release time to the current version of the release.

The CLI v2 doesn't support installing awscrt directly from dev and will require a version between `awscrt<=0.14.0,>=0.12.4` which can be found on [PyPI](https://pypi.org/project/awscrt/#history) (or installed with pip).

**Comment by gdamjan** [comment]
ah, got it

I was actually using the Archlinux package, but they seem to get the source from the github releases archive:
```
source=("https://github.com/awslabs/aws-crt-python/archive/v$pkgver/$pkgname-$pkgver.tar.gz")
```

I'll report that to them
