### ISSUE TITLE
Error on git submodule update --init

### ISSUE THREAD

**Issue by imgguti** [awslabs/aws-crt-python#426]
Cloning into 'home/pi/sdk-workspace/aws-crt-python/crt/aws-lc'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/awslabs/aws-lc.git' into submodule path 'home/pi/sdk-workspace/aws-crt-python/crt/aws-lc' failed
Failed to clone 'crt/aws-lc'. Retry scheduled
Cloning into 'home/pi/sdk-workspace/aws-crt-python/crt/aws-lc'...
error: RPC failed, curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/awslabs/aws-lc.git' into submodule path 'home/pi/sdk-workspace/aws-crt-python/crt/aws-lc' failed
Failed to clone 'crt/aws-lc' a second time, aborting

**Comment by bretambrose** [comment]
This does not appear to be a problem with the CRT.
