### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by knightjoel** [awslabs/aws-crt-python#447]
I've been working on bringing support for OpenBSD to the downstream CRT components and s2n-tls. That work is done now and everything builds and tests. The last part is to bring those changes into the Python bindings.

This issue is to request a bump of the CRT submodules to enable building the Python bindings on OpenBSD.

- c-common [v0.8.10](https://github.com/awslabs/aws-c-common/releases/tag/v0.8.10) or newer
- c-io [v0.13.15](https://github.com/awslabs/aws-c-io/releases/tag/v0.13.15) or newer
- https://github.com/awslabs/aws-c-cal/commit/de2f0f2e86a7e7b85b28cc027b8cf620945d8825 or later (no tag picks up this commit yet)
- aws-lc [v1.5.0](https://github.com/aws/aws-lc/releases/tag/v1.5.0) or newer

**Comment by knightjoel** [comment]
Thanks for this, @graebm. Unfortunately, aws-lc v1.4.0 doesn't pull in OpenBSD support (https://github.com/aws/aws-lc/commit/3c0ddb1e2f4b9dc3cb8f98b2dcda48ae8274f324). v1.5.0 was tagged a short while ago which does pull it in.

**Comment by graebm** [comment]
yeah, aws-lc v1.5.0 went out RIGHT after I updated everything else to the latest release

anyway, I pushed aws-lc to the `fix/build_on_openbsd` branch over here: https://github.com/awslabs/aws-crt-python/pull/448
