### ISSUE TITLE
undefined symbol: aes_hw_encrypt

### ISSUE THREAD

**Issue by kharalanov** [awslabs/aws-crt-python#461]
Hi - I'm compiling and installing awsiotsdk on Intel Arria10 SoC (ARM Cortex-A9). 
I'm using buildroot 2023.02. The Linux kernel is v4.14.
I've tried both Python 3.10 and 3.11 as well as GCC 8.5.0 and GCC 10.3.1.
In both cases the compile and installation works fine with single warning about the GCC not supported due to a memcmp related bug reported although it looks like this bug was fixed in those particular versions of the compilers.  

Here is the full error:

Python 3.11.2 (main, Mar 15 2023, 13:25:30) [GCC 10.3.1 20210621] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import awsiot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/awsiot/__init__.py", line 14, in <module>
  File "/usr/lib/python3.11/site-packages/awscrt/mqtt.py", line 9, in <module>
ImportError: /usr/lib/python3.11/site-packages/_awscrt.cpython-311-arm-linux-gnueabihf.so: undefined symbol: aes_hw_encrypt

Attached is the full build log.
Thanks
[awscrt_build_log.txt](https://github.com/awslabs/aws-crt-python/files/10996342/awscrt_build_log.txt)

**Comment by graebm** [comment]
What version are you using?
Version [0.16.12](https://github.com/awslabs/aws-crt-python/releases/tag/v0.16.12) released 3 days ago and may fix your issue

**Comment by graebm** [comment]
oh, yes, you're using 0.16.12, I see in the logs.

**Comment by graebm** [comment]
This seems similar to https://github.com/awslabs/aws-crt-python/issues/444
Cross-compiling with [buildroot](https://buildroot.org/) isn't something we know how to do yet

**Comment by kharalanov** [comment]
Hi @graebm - Thanks for the link to #444. This actually helped. Looks like buildroot or some other config script is not setting correctly the processor type to arm. The only change I made was to add this to crt/CMakeList.txt:
`set(CMAKE_SYSTEM_NAME Linux)`
`set(CMAKE_SYSTEM_PROCESSOR arm)`
I don't get the error anymore and and I can publish to and receive from the AWS IOT Core. I think we can close this issue.
