### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by set-soft** [awslabs/aws-crt-python#486]
### Describe the feature

Add support for Android targets

### Use Case

The [Kivy](http://kivy.org) tool can create portable Python applications that runs on Android.

It uses [Python 4 android](https://github.com/kivy/python-for-android) and [buildozer](https://github.com/kivy/buildozer) to create the APK.

### Proposed Solution

I guess this is something possible because the _aws-c-*_ already compiles for Android, to create _aws-crt-java_ for Android.

But the _builder.json_ config disables android with a comment *disabled until we have a reason to support python on android*, so perhaps this is a reason ;-)

### Other Information

P4A is supposed to support compiling C extensions from sources using _recipes_. I tried it but faced many problems, the particular way *pthreads* are handled on Android (cmake fails to detect it) and cross-compiling issues (the ARCH wrongly detected). After reading #444 I realized that this isn't trivial.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
Sorry, but this is not something that we plan on adding support for anytime soon. Closing this feature request
