### ISSUE TITLE
Issue installing on Raspbian with GCC 8.3.0

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-crt-python#76]
Hi!

I ran into multiple issues trying to install awscrt on Raspbian due to warnings (**stringop-truncation** and **cast-function-type**) being treated as errors, thus failing the build.

I managed to install it with the following command:

    CFLAGS="-Wno-stringop-truncation -Wno-cast-function-type" pip3 install awscrt

**GCC version**: 8.3.0-6+rpi1
**PIP version**: 18.1
**Python version**: 3.7.3
**CMake version**: 3.13.4

**Comment by justinboswell** [comment]
Do you happen to have a log of the warnings? If not, I'll see if I can repro and fix them up. Thanks for the report!

**Comment by bretambrose** [comment]
Some raspberry pi build issues were fixed recently, which should address your original issue.
